package com.microsoft.recognizers.text.tests;

public enum Models {
    Number,
    NumberPercentMode,
    Ordinal,
    Percent,
    PercentPercentMode,
    NumberRange,
    CustomNumber,
    Age,
    Currency,
    Dimension,
    Temperature,
    DateTime,
    DateTimeSplitDateAndTime,
    DateTimeCalendarMode,
    DateTimeExtendedTypes,
    DateTimeComplexCalendar,
    PhoneNumber,
    IpAddress,
    Mention,
    Hashtag,
    Email,
    URL,
    Boolean,
}
