from .base_numbers import BaseNumbers


# pylint: disable=line-too-long


class ArabicNumericWithUnit:
    CurrencySuffixList = dict([("Abkhazian apsar", "أبخازية أبسار"),
                               ("Afghan afghani", "أفغاني أفغاني|؋|الأفغاني|أفغاني"),
                               ("Pul", "بول"),
                               ("Euro", "EUR|يورو|اليورو|€|يورو"),
                               ("Cent", "سنتا|سنت|-سنتا|-سنت"),
                               ("Albanian lek", "ليك الألباني|ليك|ليك"),
                               ("Qindarkë", "qindarkë|qindarkës|qindarke|qindarkes"),
                               ("Angolan kwanza", "كوانزا الأنغولية|kz|aoa|كوانزا|كوانزاس|الكوانزا الأنغولية"),
                               ("Armenian dram", "الدرام الأرمنية|الدراما الأرمنية"),
                               ("Aruban florin", "فلورين أروبي|ƒ|awg|فلورين أروبي"),
                               ("Bangladeshi taka", "تاكا بنجلاديشي|৳|bdt|تاكا|تاكاس|تاكا بنجلاديشي"),
                               ("Paisa", "بويشا|بيسا"),
                               ("Bhutanese ngultrum", "نولتروم بوتاني|نو.|btn"),
                               ("Chetrum", "شيتروم|شيتروم"),
                               ("Bolivian boliviano",
                                "بوليفيانو بوليفي|بوب|بكالوريوس|بوليفيا بوليفيانو|بوليفيا بوليفيا|بوليفيانو بوليفي"),
                               ("Bosnia and Herzegovina convertible mark",
                                "علامة البوسنة والهرسك القابلة للتحويل | بام"),
                               ("Fening", "fenings|fenings"),
                               ("Botswana pula", "بولا بوتسوانا|bwp|بولا|بولا|بولا بوتسوانا"),
                               ("Thebe", "ويكون"),
                               ("Brazilian real", "ريال برازيلي|r$|brl|ريال برازيلي|ريال برازيلي|ريال برازيلي"),
                               ("Bulgarian lev", "ليف بلغاري|bgn|лв|ليف بلغاريا|ليف بلغاري|ليف بلغاري"),
                               ("Stotinka", "ستوتينكي|ستوتينكا"),
                               ("Cambodian riel", "رييل كمبودي|khr|៛|رييل كمبودي|رييل كمبودي|رييل كمبودي"),
                               ("Cape Verdean escudo", "اسكودو الرأس الأخضر|cve"),
                               ("Costa Rican colón",
                                "القولون الكوستاريكي|الكولون الكوستاريكي|crc|₡|الكولون الكوستاريكي|الكولون الكوستاريكي|الكولون الكوستاريكي|الكولون الكوستاريكي|الكولون الكوستاريكي|الكولون الكوستاريكي"),
                               ("Salvadoran colón",
                                "svc|الكولون السلفادوري|الكولون السلفادوري|الكولون السلفادور|الكولون السلفادور|الكولون السلفادوري|الكولون السلفادوري|الكولون السلفادوري|الكولون السلفادور"),
                               ("Céntimo", "سنتيمو"),
                               (
                               "Croatian kuna", "كونا كرواتية|kn|hrk|كونا كرواتيا|كونا كرواتية|كونا كرواتية"),
                               ("Lipa", "ليبا"),
                               ("Czech koruna", "الكورونا التشيكية|czk|kč|الكورونا التشيكية"),
                               ("Haléř", "هالي"),
                               ("Eritrean nakfa", "الناكفا الإريترية|nfk|ern|الناكفا الإريترية"),
                               ("Ethiopian birr", "بير إثيوبي|etb"),
                               ("Gambian dalasi", "gmd"),
                               ("Butut", "بوتات|بوتوت"),
                               ("Georgian lari", "لاري جورجي|لاري|جل|₾"),
                               ("Tetri", "تتري"),
                               ("Ghanaian cedi", "السيدي الغاني|ghs|₵|gh₵"),
                               ("Pesewa", "بيسيوا|بيسيوا"),
                               ("Guatemalan quetzal", "الكوازال الغواتيمالي|gtq|الكوازال الغواتيمالي"),
                               ("Haitian gourde", "غورد هايتي|htg"),
                               ("Honduran lempira", "لمبيرا هندوراس|hnl"),
                               ("Hungarian forint",
                                "فورنت مجري|huf|قدم|فورنت مجري|فورنت مجري|فورنت مجري"),
                               ("Fillér", "حشو"),
                               ("Iranian rial", "الريال الإيراني|irr|الريال الإيراني|الريال الإيراني|الريال الإيراني"),
                               ("Yemeni rial", "ريال يمني|يير|ريال يمني"),
                               ("Israeli new shekel", "₪|إيلس|أغورا"),
                               ("Lithuanian litas", "ltl|ليتاس الليتواني|ليتاس الليتواني|ليتاس الليتواني|ليتاس الليتواني"),
                               ("Japanese yen", "ين ياباني|ين ياباني|ين|-ين|¥|ين|ين ياباني|ين ياباني|ين ياباني"),
                               ("Kazakhstani tenge", "تنغي كازاخستاني|تنغي كازاخستاني|تنغي كازاخستاني|كزت"),
                               ("Kenyan shilling", "شلن كيني|كيس"),
                               ("North Korean won", "وون كوريا الشمالية|kpw|وون كوريا الشمالية"),
                               ("South Korean won", "وون كوريا الجنوبية|krw|وون كوريا الجنوبية"),
                               ("Korean won", "وون كوري|₩|وون كوري"),
                               ("Kyrgyzstani som", "سوم قيرغيزستاني|كجم"),
                               ("Uzbekitan som", "السوم الأوزبكي|uzs"),
                               ("Lao kip", "لاو كيب|لاك|₭ن|₭"),
                               ("Att", "أت"),
                               ("Lesotho loti", "لوتي ليسوتو|lsl|لوتي"),
                               ("Sente", "استماع|استماع"),
                               ("South African rand",
                                "راند جنوب أفريقيا|زار|راند جنوب أفريقيا|راند جنوب أفريقيا|راند جنوب أفريقيا"),
                               ("Macanese pataca", "باتاكا ماكاوية|ممسحة$|ممسحة"),
                               ("Avo", "تجنب|تجنب"),
                               ("Macedonian denar", "دينار مقدوني|mkd|ден"),
                               ("Deni", "ديني"),
                               ("Malagasy ariary", "ارياري مدغشقر|mga"),
                               ("Iraimbilanja", "iraimbilanja"),
                               ("Malawian kwacha", "كواشا ملاوية|mk|mwk"),
                               ("Tambala", "تامبالا"),
                               ("Malaysian ringgit",
                                "رينغيت ماليزيا|rm|مير|رينغيت ماليزيا|رينغيت ماليزيا|رينغيت ماليزيا"),
                               ("Mauritanian ouguiya",
                                "أوقية موريتانية|أم|مرو|أوقية موريتانية|أوقية موريتانية|أوقية موريتانية"),
                               ("Khoums", "الخمس"),
                               ("Mongolian tögrög",
                                "توجروج منغولي|mnt|₮|توجروج منغوليا|توجروج منغوليا|توجروج منغولي|توجروج منغولي|توجروج منغولي|توجروج منغولي|توجروج منغوليا|توجروج منغولي"),
                               ("Mozambican metical",
                                "ميتيكال موزمبيق|mt|mzn|ميتيكال موزمبيق|ميتيكال موزمبيق|ميتيكال موزمبيق"),
                               ("Burmese kyat", "كيات البورمية|ks|mmk"),
                               ("Pya", "بيا"),
                               ("Nicaraguan córdoba", "كوردوبا النيكاراغوية|نيو"),
                               ("Nigerian naira",
                                "نايرا نيجيري|نايرا|ngn|₦|نايرا نيجيري|نايرا نيجيري|نايرا نيجيري"),
                               ("Kobo", "كوبو"),
                               ("Turkish lira", "الليرة التركية|try|tl|الليرة التركية|الليرة التركية|الليرة التركية"),
                                   ("Kuruş", "kuruş"),
                               ("Omani rial", "ريال عماني|عمر|ر.ع."),
                               ("Panamanian balboa", "بالبوا البنمي|ب/.|pab"),
                               ("Centesimo", "سنتيسيمو"),
                               ("Papua New Guinean kina", "بابوا غينيا الجديدة كينا|كينا|pgk"),
                               ("Toea", "إلى عصام"),
                               ("Paraguayan guaraní", "غواراني باراغواي|₲|pyg"),
                               ("Peruvian sol", "سول بيرو|النعال|سول|سول بيرو الجديد"),
                               ("Polish złoty",
                                "زلوتي|زلوتي بولندي|zł|pln|زلوتي|زلوتي بولندي|زلوتي بولندا|زلوتي بولندا"),
                               ("Grosz", "جروزي|جروز|جروزي"),
                               ("Qatari riyal", "ريال قطري|قار|ريال قطري|ريال قطري|ريال قطري"),
                               ("Saudi riyal", "الريال السعودي|الريال|الريال السعودي"),
                               ("Riyal", "ريال|ريال|ريال|﷼"),
                               ("Dirham", "درهم|درهم|درهم"),
                               ("Halala", "هللة|هللة"),
                               ("Samoan tālā", "تالا ساموا|تالا|تالا|ws$|ساموا|غرب|تالا ساموا"),
                               ("Sene", "سيني"),
                               ("São Tomé and Príncipe dobra", "ساو تومي وبرينسيبي دوبرا|دوبراس|دوبرا"),
                               ("Sierra Leonean leone", "ليون سيراليوني|sll|ليون|le"),
                               ("Peseta", "بيزيتا|بيسيتا"),
                               ("Netherlands guilder",
                                "فلورين|جلدر جزر الأنتيل|ang|جولدن هولندا|الغيلدر|الغيلدر|-الغيلدر|-الغيلدر|الغيلدر الهولندي|الغيلدر الهولندي|fl"),
                               ("Swazi lilangeni", "ليلانجيني سوازي|ليلانجيني|szl|إيمالانجيني"),
                               ("Tajikistani somoni", "السوموني الطاجيكي|tjs|السوموني"),
                               ("Diram", "درام|درم"),
                               ("Thai baht", "باهت تايلاندي|฿|thb|باهت"),
                               ("Satang", "ساتانغ|ساتانغ"),
                               ("Tongan paʻanga", "بانجا تونجا|بانجا|بانجا تونجا|باانجانج"),
                               ("Seniti", "سينيتي"),
                               ("Ukrainian hryvnia",
                                "هريفنيا أوكرانية|هريفنيا|uah|₴|هريفنيا أوكرانيا|هريفنيا أوكرانيا|هريفنيا أوكرانية"),
                               ("Vanuatu vatu", "فانواتو فاتو|فاتو|فوف"),
                               ("Venezuelan bolívar",
                                "بوليفار فنزويلا|بوليفار فنزويلا|bs.f.|vef|بوليفار فويرتي|بوليفار فنزويلا|بوليفار فنزويلا|بوليفار فنزويلا|بوليفار فنزويلا|بوليفار فنزويلا|بوليفار فنزويلا|بوليفار فنزويلا"),
                               ("Vietnamese dong",
                                "دونج فيتنام|vnd|دونج|دونج فيتنام|دونج فيتنام|دونج فيتنام"),
                               ("Zambian kwacha", "كواشا زامبيا|zk|zmw|كواشا زامبيا|كواشا|كواشا زامبيا"),
                               ("Moroccan dirham", "درهم مغربي|mad|د.م."),
                               ("United Arab Emirates dirham", "درهم الإمارات العربية المتحدة|د.إ|aed"),
                               ("Azerbaijani manat", "مانات أذربيجان|azn"),
                               ("Turkmenistan manat", "مانات تركمانستان|مانات تركمانستان الجديد|tmt"),
                               ("Manat", "مانات|مانات"),
                               ("Qəpik", "qəpik"),
                               ("Somali shilling",
                                "شلن صومالي|شلن صومالي|شيلين صومالي|-شيلين صومالي|scellino|shilin|sh.so.|sos"),
                               ("Somaliland shilling", "شلن صوماليلاند|شلن صوماليلاند|سوماليلاند شيلين"),
                               ("Tanzanian shilling",
                                "شلن تنزاني|شلن تنزاني|tsh|tzs|شلن تنزاني|شلن تنزاني"),
                               ("Ugandan shilling",
                                "شلن أوغندي|شلن أوغندي|ugx|شلن أوغندي|شلن أوغندي"),
                               ("Romanian leu", "ليو الروماني|ليو|رون|ليو رومانيا"),
                               ("Moldovan leu", "ليو مولدوفا|mdl|ليو مولدوفا"),
                               ("Leu", "ليو"),
                               ("Ban", "بني|-حظر|حظر"),
                               ("Nepalese rupee", "روبية نيبالية|روبية نيبالية|npr"),
                               ("Pakistani rupee", "الروبية الباكستانية|الروبية الباكستانية|pkr"),
                               ("Indian rupee", "روبية هندية|روبية هندية|inr|₹|روبية هندية|روبية هندية"),
                               ("Seychellois rupee", "روبية سيشيلية|روبية سيشيلية|scr|sr|sre"),
                               ("Mauritian rupee", "روبية موريشيوسية|روبية موريشيوسية|مور"),
                               ("Maldivian rufiyaa",
                                "روفية جزر المالديف|روفية جزر المالديف|mvr|.य|روفية جزر المالديف|روفية جزر المالديف"),
                               ("Sri Lankan rupee", "روبية سريلانكية|روبية سريلانكية|lkr|රු|ரூ"),
                               ("Indonesian rupiah", "الروبية الإندونيسية|الروبية|بيراك|RP|IDR"),
                               ("Rupee", "روبية|روبية|رس"),
                               ("Danish krone", "الكرونة الدنماركية|dkk|الكرونة الدنماركية|الكرونة الدنماركية|الكرونة الدنماركية"),
                               ("Norwegian krone", "كرونة نرويجية|نوك|كرونة نرويجية|كرونة نرويجية|كرونة نرويجية"),
                               ("Faroese króna", "الكرونا الفارويزية|الكرونا الفارويزية"),
                               ("Icelandic króna", "الكرونا الايسلندية|isk|الكرونا الايسلندية|الكرونا الايسلندية|الكرونا الايسلندية"),
                               ("Swedish krona", "كرونة سويدية|سيك|كرونا سويدية"),
                               ("Krone", "كرونة|كرونا|كرونا|كرونة|كرونات|kr|-kr"),
                               ("Øre", "أوري|أويرا|إيرير"),
                               ("West African CFA franc",
                                "فرنك غرب أفريقيا|xof|فرنك غرب أفريقيا|فرنك غرب أفريقيا|فرنك غرب أفريقيا"),
                               ("Central African CFA franc",
                                "فرنك وسط أفريقيا|xaf|فرنك وسط أفريقيا|فرنك وسط أفريقيا|فرنك وسط أفريقيا"),
                               ("Comorian franc", "فرنك جزر القمر|كمف"),
                               ("Congolese franc", "الفرنك الكونغولي|cdf"),
                               ("Burundian franc", "الفرنك البوروندي|bif"),
                               ("Djiboutian franc", "الفرنك الجيبوتي|djf"),
                               ("CFP franc", "فرنك CFP|xpf"),
                               ("Guinean franc", "الفرنك الغيني|gnf"),
                               ("Swiss franc", "فرنك سويسري|فرنك سويسري|فرنك سويسري|فرنك سويسري."),
                               ("Rwandan franc", "الفرنك الرواندي|rwf|rf|r₣|frw"),
                               ("Belgian franc", "الفرنك البلجيكي|bi.|b.fr.|bef|الفرنك البلجيكي"),
                               ("Rappen", "رابن|-رابين"),
                               ("Franc", "فرنك|فرنك|فرنك|fs"),
                               ("Centime", "سنتيم|سنتيم|سانتيم"),
                               ("Russian ruble",
                                "روبل روسي|₽|فرك|روبل روسي|روسيا ₽|روسي ₽|روبل روسي|روبل روسي"),
                               ("New Belarusian ruble",
                                "روبل بيلاروسي جديد|byn|روبل بيلاروسي جديد|روبل بيلاروسي جديد|روبل بيلاروسي جديد"),
                               ("Old Belarusian ruble",
                                "روبل بيلاروسي قديم|بير|روبل بيلاروسي قديم|روبل بيلاروسي قديم|روبل بيلاروسي قديم"),
                               ("Transnistrian ruble", "روبل ترانسنيستريا|prb|Р."),
                               ("Belarusian ruble", "روبل بيلاروسي|روبل بيلاروسي|روبل بيلاروسيا|روبل بيلاروسي"),
                               ("Kopek", "كوبيك|كوبيك"),
                               ("Kapyeyka", "kapyeyka"),
                               ("Ruble", "rأوبلس|روبل|ر"),
                               (
                               "Algerian dinar", "دينار جزائري|د.ج|dzd|دينار جزائري|دينار جزائري|دينار جزائري"),
                               ("Bahraini dinar", "دينار بحريني|دينار بحريني|bhd|.د.ب"),
                               ("Santeem", "سانتيم|سانتيم"),
                               ("Iraqi dinar", "دينار عراقي|دينار عراقي|دينار عراقي|دينار عراقي|iqd|ع.د"),
                               ("Jordanian dinar",
                                "دينار أردني|دينار أردني|د.ا|جود|دينار أردني|دينار أردني"),
                               ("Kuwaiti dinar", "دينار كويتي|دينار كويتي|كود|د.ك"),
                               ("Libyan dinar", "دينار ليبي|دينار ليبي|دينار ليبي|دينار ليبي|ليد"),
                               ("Serbian dinar",
                                "دينار صربي|دينار صربي|دين.|rsd|дин.|دينار صربيا|دينار صربيا"),
                               ("Tunisian dinar", "دينار تونسي|دينار تونسي|tnd|دينار تونسي|دينار تونسي"),
                               ("Yugoslav dinar", "دينار يوغوسلافي|دينار يوغوسلافي|يون"),
                               ("Dinar", "دينار|دينار|دينار|-دينار|-دينار"),
                               ("Fils", "فلس|فولوس|-فلس|-فيل"),
                               ("Para", "بارا|نابا"),
                               ("Millime", "مليم|مليم"),
                               ("Argentine peso", "بيزو أرجنتيني|ars|بيزو أرجنتيني|بيزو أرجنتيني|بيزو أرجنتيني"),
                               ("Chilean peso", "بيزو شيلي|بيزو تشيلي|clp|بيزو شيلي|بيزو تشيلي"),
                               ("Colombian peso", "البيزو الكولومبي|البيزو الكولومبي|شرطي|البيزو الكولومبي|البيزو الكولومبي"),
                               ("Cuban convertible peso",
                                "البيزو الكوبي القابل للتحويل|البيزو الكوبي القابل للتحويل|cuc|البيزو الكوبي القابل للتحويل|البيزو الكوبي القابل للتحويل"),
                               ("Cuban peso", "بيزو كوبي | بيزو كوبي | كوب | بيزو كوبا | بيزو كوبا"),
                               ("Dominican peso", "بيزو دومينيكي|بيزو دومينيكي|dop|بيزو دومينيكا|بيزو دومينيكا"),
                               ("Mexican peso",
                                "البيزو المكسيكي|البيزو المكسيكي|mxn|البيزو المكسيكي|البيزو المكسيكي|mxn$|mxn $|mex$"),
                               ("Philippine peso", "بيزو|بيزو فلبيني|بيزو فلبيني|₱|php"),
                               ("Uruguayan peso", "بيزو أوروغواي|بيزو أوروغواي|uyu₱|php"),
                               ("Peso", "بيزو|بيزو"),
                               ("Centavo", "سنتافو|سنتافو"),
                               ("Alderney pound", "جنيه ألدرني|جنيه ألدرني|جنيه ألدرني"),
                               ("British pound",
                                "الجنيه البريطاني|الجنيه الاسترليني|الجنيه الاسترليني|الجنيه الاسترليني|الجنيه الاسترليني|الجنيه الاسترليني|الجنيه الاسترليني|الجنيه الاسكتلندي|الجنيه الاسكتلندي"),
                               ("Guernsey pound", "جنيه جيرنسي|جيرنسي جنيه استرليني|ggp"),
                               ("Ascension pound", "جنيه الصعود|جنيه الصعود|جنيه الصعود"),
                               ("Saint Helena pound", "جنيه سانت هيلينا|جنيه سانت هيلينا|جنيه سانت هيلينا جنيه استرليني|shp"),
                               ("Egyptian pound",
                                "جنيه مصري|جنيه مصري|جنيه إسترليني|egp|ج.م|جنيه مصري|جنيه مصري"),
                               ("Falkland Islands pound",
                                "جنيه جزر فوكلاند|جنيه جزر فوكلاند|جنيه جزر فوكلاند|جنيه استرليني|fkp|جنيه جزيرة فوكلاند|جنيه جزيرة فوكلاند|جنيه جزيرة فوكلاند"),
                               ("Gibraltar pound", "جنيه جبل طارق|جنيه جبل طارق|جنيه جبل طارق|gip"),
                               ("Manx pound", "جنيه مانكس|جنيه مانكس|جنيه مانكس|عفريت"),
                               ("Jersey pound", "جنيه جيرسي | جنيه جيرسي | جنيه إسترليني جيرسي | جيب"),
                               ("Lebanese pound",
                                "ليرة لبنانية|ليرة لبنانية|ليرة لبنانية|ليرة لبنانية|ليرة لبنانية|ليرة لبنانية|ليرة لبنانية|ل.ل"),
                               ("South Georgia and the South Sandwich Islands pound",
                                "جورجيا الجنوبية وجزر ساندويتش الجنوبية جنيه إسترليني|جورجيا الجنوبية وجزر ساندويتش الجنوبية جنيه إسترليني|جورجيا الجنوبية وجزر ساندويتش الجنوبية جنيه إسترليني"),
                               ("South Sudanese pound",
                                "جنيه جنوب السودان|جنيه جنوب السودان|جنيه جنوب السودان|ssp|جنيه جنوب السودان|جنيه جنوب السودان|جنيه جنوب السودان"),
                               ("Sudanese pound",
                                "جنيه سوداني|جنيه سوداني|جنيه سوداني|ج.س.|sdg|جنيه سوداني|جنيه سوداني|جنيه سوداني"),
                               ("Syrian pound",
                                "ليرة سورية|ليرة سورية|ليرة سورية|ل.س|syp|ليرة سورية|ليرة سورية|ليرة سورية"),
                               ("Tristan da Cunha pound",
                                "جنيه تريستان دا كونيا|جنيه تريستان دا كونيا|جنيه تريستان دا كونيا"),
                               ("Pound", "جنيه|جنيه|-جنيه|-جنيه|جنيه إسترليني"),
                               ("Pence", "بنس"),
                               ("Shilling", "شلن|شلن|شيلنجي|ش"),
                               ("Penny", "بينس|بيني"),
                               ("United States dollar",
                                "دولارات الولايات المتحدة|دولار الولايات المتحدة|الولايات المتحدة $|الولايات المتحدة. دولار|الولايات المتحدة. دولار|دولار أمريكي|دولار أمريكي|USD|دولار أمريكي|دولار أمريكي|دولار أمريكي|دولار أمريكي|دولار أمريكي|دولار أمريكي|دولار أمريكي|USD$"),
                               ("East Caribbean dollar",
                                "دولار شرق الكاريبي|دولار شرق الكاريبي|دولار شرق الكاريبي $|xcd"),
                               ("Australian dollar",
                                "دولار أسترالي|دولار أسترالي|دولار أسترالي|أسترالي$|AUD|دولار أسترالي|دولار أسترالي|أسترالي $|أسترالي$"),
                               ("Bahamian dollar",
                                "دولار بهامي|دولار بهامي|دولار بهامي $|دولار بهامي$|bsd|دولار بهامي|دولار بهامي|باهامي $|باهامي$"),
                               ("Barbadian dollar", "دولار بربادوسي|دولار بربادوسي|دولار بربادوسي|bbd"),
                               ("Belize dollar", "دولار بليز|دولار بليز|دولار بليز|bzd"),
                               ("Bermudian dollar",
                                "دولار برمودي|دولار برمودي|دولار برمودي|دولار برمودي|دولار برمودي|دولار برمودي|دولار برمودي"),
                               ("British Virgin Islands dollar",
                                "دولار جزر فيرجن البريطانية|دولار جزر فيرجن البريطانية|جزر فيرجن البريطانية $|bvi$|دولار جزر فيرجن|دولار جزر فيرجن|جزر فيرجن $|دولار جزر فيرجن|دولار جزيرة فيرجن|دولار جزيرة فيرجن $"),
                               ("Brunei dollar", "دولار بروناي|دولار بروناي $|مليار دولار"),
                               ("Sen", "سين"),
                               ("Singapore dollar", "دولار سنغافوري|دولار سنغافوري|دولار سنغافوري $|s$|sgd"),
                               ("Canadian dollar",
                                "دولار كندي|دولار كندي|دولار كندي|دولار كندي|can$|c$|دولار كندي|دولار كندي|كندا$"),
                               ("Cayman Islands dollar",
                                "دولار جزر كايمان|دولار جزر كايمان|جزر كايمان $|kyd|ci$|دولار جزر كايمان|دولارات جزر كايمان|دولار جزر كايمان $"),
                               ("New Zealand dollar",
                                "دولار نيوزيلندي|دولار نيوزيلندي|نيوزيلندا $|nz$|nzd|كيوي"),
                               ("Cook Islands dollar",
                                "دولار جزر كوك|دولار جزر كوك|جزر كوك $|دولار جزر كوك|دولار جزيرة كوك|جزيرة كوك $"),
                               ("Fijian dollar",
                                "دولار فيجي|دولار فيجي|دولار فيجي|دولار فيجي|دولار فيجي|دولار فيجي|دولار فيجي"),
                               ("Guyanese dollar", "دولار جوياني|دولار جوياني|gyd|gy$"),
                               ("Hong Kong dollar",
                                "دولار هونج كونج|دولار هونج كونج|دولار هونج كونج|$hk$|hkd|دولار هونج كونج|دولار هونج كونج|دولار هونج كونج|دولار هونج كونج|دولار هونج كونج"),
                               ("Jamaican dollar",
                                "دولار جامايكي|دولار جامايكي|دولار جامايكي|j$|دولار جامايكي|دولار جامايكي|جامايكا $|JMD"),
                               ("Kiribati dollar", "دولار كيريباتي|دولار كيريباتي|دولار كيريباتي"),
                               ("Liberian dollar",
                                "دولار ليبيري|دولار ليبيري|دولار ليبيري|دولار ليبيري|دولار ليبيري|ليبيري $|ليرة لبنانية"),
                               ("Micronesian dollar", "دولار ميكرونيزي | دولار ميكرونيزي | دولار ميكرونيزي"),
                               ("Namibian dollar",
                                "دولار ناميبي|دولار ناميبي|دولار ناميبي|ناد|n$|دولار ناميبي|دولار ناميبي|ناميبيا $"),
                               ("Nauruan dollar", "دولار ناورو|دولار ناورو|دولار ناورو"),
                               ("Niue dollar", "دولار نيوي|دولار نيوي|دولار نيوي"),
                               ("Palauan dollar", "دولار بالاو | دولار بالاو | دولار بالاو"),
                               ("Pitcairn Islands dollar",
                                "دولارات جزر بيتكيرن|دولار جزر بيتكيرن|دولارات جزر بيتكيرن $|دولار جزيرة بيتكيرن|دولار جزيرة بيتكيرن|دولار جزيرة بيتكيرن $"),
                               ("Solomon Islands dollar",
                                "دولار جزر سليمان|دولار جزر سليمان|جزر سليمان $|si$|sbd|دولار جزر سليمان|دولار جزيرة سليمان|جزر سليمان $"),
                               ("Surinamese dollar", "دولار سورينام|دولار سورينامي|دولار سورينام|ريال سعودي"),
                               ("New Taiwan dollar", "دولار تايواني جديد|دولار تايواني جديد|nt$|twd|ntd"),
                               ("Trinidad and Tobago dollar",
                                "دولار ترينداد وتوباغو|دولار ترينداد وتوباغو|دولار ترينداد وتوباغو $|ترينداد $|دولار ترينداد|دولار ترينداد|دولار ترينيدادي|دولار ترينيدادي|دولار ترينيدادي $|ttd"),
                               ("Tuvaluan dollar", "دولار توفالو|دولار توفالو|دولار توفالو"),
                               ("Dollar", "دولار|دولار|$"),
                               ("Chinese yuan", "يوان|كواي|يوان صيني|رنمينبي|cny|رنمينبي|￥|元"),
                               ("Fen", "الفين"),
                               ("Jiao", "جياو|ماو"),
                               ("Finnish markka", "سومن ماركا|ماركا الفنلندية|فينسك مارك|فيم|ماركا|ماركا"),
                               ("Penni", "بينيا|بيني"),
                               ("Bitcoin", "بيتكوين|بيتكوينز|btc|xbt|₿"),
                               ("Millibitcoin", "ميلي بيتكوين| ميلي بيتكوين | ميلي بيتكوين | ميلي بيتكوين"),
                               ("Satoshi", "ساتوشي|ساتوشي")])
    CurrencyNameToIsoCodeMap = dict([("Afghan afghani", "AFN"),
                                     ("Euro", "EUR"),
                                     ("Albanian lek", "ALL"),
                                     ("Angolan kwanza", "AOA"),
                                     ("Armenian dram", "AMD"),
                                     ("Aruban florin", "AWG"),
                                     ("Bangladeshi taka", "BDT"),
                                     ("Bhutanese ngultrum", "BTN"),
                                     ("Bolivian boliviano", "BOB"),
                                     ("Bosnia and Herzegovina convertible mark", "BAM"),
                                     ("Botswana pula", "BWP"),
                                     ("Brazilian real", "BRL"),
                                     ("Bulgarian lev", "BGN"),
                                     ("Cambodian riel", "KHR"),
                                     ("Cape Verdean escudo", "CVE"),
                                     ("Costa Rican colón", "CRC"),
                                     ("Croatian kuna", "HRK"),
                                     ("Czech koruna", "CZK"),
                                     ("Eritrean nakfa", "ERN"),
                                     ("Ethiopian birr", "ETB"),
                                     ("Gambian dalasi", "GMD"),
                                     ("Georgian lari", "GEL"),
                                     ("Ghanaian cedi", "GHS"),
                                     ("Guatemalan quetzal", "GTQ"),
                                     ("Haitian gourde", "HTG"),
                                     ("Honduran lempira", "HNL"),
                                     ("Hungarian forint", "HUF"),
                                     ("Iranian rial", "IRR"),
                                     ("Yemeni rial", "YER"),
                                     ("Israeli new shekel", "ILS"),
                                     ("Japanese yen", "JPY"),
                                     ("Kazakhstani tenge", "KZT"),
                                     ("Kenyan shilling", "KES"),
                                     ("North Korean won", "KPW"),
                                     ("South Korean won", "KRW"),
                                     ("Kyrgyzstani som", "KGS"),
                                     ("Lao kip", "LAK"),
                                     ("Lesotho loti", "LSL"),
                                     ("South African rand", "ZAR"),
                                     ("Macanese pataca", "MOP"),
                                     ("Macedonian denar", "MKD"),
                                     ("Malagasy ariary", "MGA"),
                                     ("Malawian kwacha", "MWK"),
                                     ("Malaysian ringgit", "MYR"),
                                     ("Mauritanian ouguiya", "MRO"),
                                     ("Mongolian tögrög", "MNT"),
                                     ("Mozambican metical", "MZN"),
                                     ("Burmese kyat", "MMK"),
                                     ("Nicaraguan córdoba", "NIO"),
                                     ("Nigerian naira", "NGN"),
                                     ("Turkish lira", "TRY"),
                                     ("Omani rial", "OMR"),
                                     ("Panamanian balboa", "PAB"),
                                     ("Papua New Guinean kina", "PGK"),
                                     ("Paraguayan guaraní", "PYG"),
                                     ("Peruvian sol", "PEN"),
                                     ("Polish złoty", "PLN"),
                                     ("Qatari riyal", "QAR"),
                                     ("Saudi riyal", "SAR"),
                                     ("Samoan tālā", "WST"),
                                     ("São Tomé and Príncipe dobra", "STN"),
                                     ("Sierra Leonean leone", "SLL"),
                                     ("Swazi lilangeni", "SZL"),
                                     ("Tajikistani somoni", "TJS"),
                                     ("Thai baht", "THB"),
                                     ("Ukrainian hryvnia", "UAH"),
                                     ("Vanuatu vatu", "VUV"),
                                     ("Venezuelan bolívar", "VEF"),
                                     ("Zambian kwacha", "ZMW"),
                                     ("Moroccan dirham", "MAD"),
                                     ("United Arab Emirates dirham", "AED"),
                                     ("Azerbaijani manat", "AZN"),
                                     ("Turkmenistan manat", "TMT"),
                                     ("Somali shilling", "SOS"),
                                     ("Tanzanian shilling", "TZS"),
                                     ("Ugandan shilling", "UGX"),
                                     ("Romanian leu", "RON"),
                                     ("Moldovan leu", "MDL"),
                                     ("Nepalese rupee", "NPR"),
                                     ("Pakistani rupee", "PKR"),
                                     ("Indian rupee", "INR"),
                                     ("Seychellois rupee", "SCR"),
                                     ("Mauritian rupee", "MUR"),
                                     ("Maldivian rufiyaa", "MVR"),
                                     ("Sri Lankan rupee", "LKR"),
                                     ("Indonesian rupiah", "IDR"),
                                     ("Danish krone", "DKK"),
                                     ("Norwegian krone", "NOK"),
                                     ("Icelandic króna", "ISK"),
                                     ("Swedish krona", "SEK"),
                                     ("West African CFA franc", "XOF"),
                                     ("Central African CFA franc", "XAF"),
                                     ("Comorian franc", "KMF"),
                                     ("Congolese franc", "CDF"),
                                     ("Burundian franc", "BIF"),
                                     ("Djiboutian franc", "DJF"),
                                     ("CFP franc", "XPF"),
                                     ("Guinean franc", "GNF"),
                                     ("Swiss franc", "CHF"),
                                     ("Franc", "CHF"),
                                     ("Rwandan franc", "RWF"),
                                     ("Russian ruble", "RUB"),
                                     ("Transnistrian ruble", "PRB"),
                                     ("New Belarusian ruble", "BYN"),
                                     ("Algerian dinar", "DZD"),
                                     ("Bahraini dinar", "BHD"),
                                     ("Iraqi dinar", "IQD"),
                                     ("Jordanian dinar", "JOD"),
                                     ("Kuwaiti dinar", "KWD"),
                                     ("Libyan dinar", "LYD"),
                                     ("Serbian dinar", "RSD"),
                                     ("Tunisian dinar", "TND"),
                                     ("Argentine peso", "ARS"),
                                     ("Chilean peso", "CLP"),
                                     ("Colombian peso", "COP"),
                                     ("Cuban convertible peso", "CUC"),
                                     ("Cuban peso", "CUP"),
                                     ("Dominican peso", "DOP"),
                                     ("Mexican peso", "MXN"),
                                     ("Uruguayan peso", "UYU"),
                                     ("British pound", "GBP"),
                                     ("Saint Helena pound", "SHP"),
                                     ("Egyptian pound", "EGP"),
                                     ("Falkland Islands pound", "FKP"),
                                     ("Gibraltar pound", "GIP"),
                                     ("Manx pound", "IMP"),
                                     ("Jersey pound", "JEP"),
                                     ("Lebanese pound", "LBP"),
                                     ("South Sudanese pound", "SSP"),
                                     ("Sudanese pound", "SDG"),
                                     ("Syrian pound", "SYP"),
                                     ("United States dollar", "USD"),
                                     ("Australian dollar", "AUD"),
                                     ("Bahamian dollar", "BSD"),
                                     ("Barbadian dollar", "BBD"),
                                     ("Belize dollar", "BZD"),
                                     ("Bermudian dollar", "BMD"),
                                     ("Brunei dollar", "BND"),
                                     ("Singapore dollar", "SGD"),
                                     ("Canadian dollar", "CAD"),
                                     ("Cayman Islands dollar", "KYD"),
                                     ("New Zealand dollar", "NZD"),
                                     ("Fijian dollar", "FJD"),
                                     ("Guyanese dollar", "GYD"),
                                     ("Hong Kong dollar", "HKD"),
                                     ("Jamaican dollar", "JMD"),
                                     ("Liberian dollar", "LRD"),
                                     ("Namibian dollar", "NAD"),
                                     ("Solomon Islands dollar", "SBD"),
                                     ("Surinamese dollar", "SRD"),
                                     ("New Taiwan dollar", "TWD"),
                                     ("Trinidad and Tobago dollar", "TTD"),
                                     ("Tuvaluan dollar", "TVD"),
                                     ("Chinese yuan", "CNY"),
                                     ("Rial", "__RI"),
                                     ("Shiling", "__S"),
                                     ("Som", "__SO"),
                                     ("Dirham", "__DR"),
                                     ("Dinar", "_DN"),
                                     ("Dollar", "__D"),
                                     ("Manat", "__MA"),
                                     ("Rupee", "__R"),
                                     ("Krone", "__K"),
                                     ("Krona", "__K"),
                                     ("Crown", "__K"),
                                     ("Frank", "__F"),
                                     ("Mark", "__M"),
                                     ("Ruble", "__RB"),
                                     ("Peso", "__PE"),
                                     ("Pound", "__P"),
                                     ("Tristan da Cunha pound", "_TP"),
                                     ("South Georgia and the South Sandwich Islands pound", "_SP"),
                                     ("Somaliland shilling", "_SS"),
                                     ("Pitcairn Islands dollar", "_PND"),
                                     ("Palauan dollar", "_PD"),
                                     ("Niue dollar", "_NID"),
                                     ("Nauruan dollar", "_ND"),
                                     ("Micronesian dollar", "_MD"),
                                     ("Kiribati dollar", "_KID"),
                                     ("Guernsey pound", "_GGP"),
                                     ("Faroese króna", "_FOK"),
                                     ("Cook Islands dollar", "_CKD"),
                                     ("British Virgin Islands dollar", "_BD"),
                                     ("Ascension pound", "_AP"),
                                     ("Alderney pound", "_ALP"),
                                     ("Abkhazian apsar", "_AA"),
                                     ("Bitcoin", "_XBT")])
    FractionalUnitNameToCodeMap = dict([("Jiao", "JIAO"),
                                        ("Kopek", "KOPEK"),
                                        ("Pul", "PUL"),
                                        ("Cent", "CENT"),
                                        ("Qindarkë", "QINDARKE"),
                                        ("Penny", "PENNY"),
                                        ("Santeem", "SANTEEM"),
                                        ("Cêntimo", "CENTIMO"),
                                        ("Centavo", "CENTAVO"),
                                        ("Luma", "LUMA"),
                                        ("Qəpik", "QƏPIK"),
                                        ("Fils", "FILS"),
                                        ("Poisha", "POISHA"),
                                        ("Kapyeyka", "KAPYEYKA"),
                                        ("Centime", "CENTIME"),
                                        ("Chetrum", "CHETRUM"),
                                        ("Paisa", "PAISA"),
                                        ("Fening", "FENING"),
                                        ("Thebe", "THEBE"),
                                        ("Sen", "SEN"),
                                        ("Stotinka", "STOTINKA"),
                                        ("Fen", "FEN"),
                                        ("Céntimo", "CENTIMO"),
                                        ("Lipa", "LIPA"),
                                        ("Haléř", "HALER"),
                                        ("Øre", "ØRE"),
                                        ("Piastre", "PIASTRE"),
                                        ("Santim", "SANTIM"),
                                        ("Oyra", "OYRA"),
                                        ("Butut", "BUTUT"),
                                        ("Tetri", "TETRI"),
                                        ("Pesewa", "PESEWA"),
                                        ("Fillér", "FILLER"),
                                        ("Eyrir", "EYRIR"),
                                        ("Dinar", "DINAR"),
                                        ("Agora", "AGORA"),
                                        ("Tïın", "TIIN"),
                                        ("Chon", "CHON"),
                                        ("Jeon", "JEON"),
                                        ("Tyiyn", "TYIYN"),
                                        ("Att", "ATT"),
                                        ("Sente", "SENTE"),
                                        ("Dirham", "DIRHAM"),
                                        ("Rappen", "RAPPEN"),
                                        ("Avo", "AVO"),
                                        ("Deni", "DENI"),
                                        ("Iraimbilanja", "IRAIMBILANJA"),
                                        ("Tambala", "TAMBALA"),
                                        ("Laari", "LAARI"),
                                        ("Khoums", "KHOUMS"),
                                        ("Ban", "BAN"),
                                        ("Möngö", "MONGO"),
                                        ("Pya", "PYA"),
                                        ("Kobo", "KOBO"),
                                        ("Kuruş", "KURUS"),
                                        ("Baisa", "BAISA"),
                                        ("Centésimo", "CENTESIMO"),
                                        ("Toea", "TOEA"),
                                        ("Sentimo", "SENTIMO"),
                                        ("Grosz", "GROSZ"),
                                        ("Sene", "SENE"),
                                        ("Halala", "HALALA"),
                                        ("Para", "PARA"),
                                        ("Öre", "ORE"),
                                        ("Diram", "DIRAM"),
                                        ("Satang", "SATANG"),
                                        ("Seniti", "SENITI"),
                                        ("Millime", "MILLIME"),
                                        ("Tennesi", "TENNESI"),
                                        ("Kopiyka", "KOPIYKA"),
                                        ("Tiyin", "TIYIN"),
                                        ("Hào", "HAO"),
                                        ("Ngwee", "NGWEE"),
                                        ("Millibitcoin", "MILLIBITCOIN"),
                                        ("Satoshi", "SATOSHI")])
    CompoundUnitConnectorRegex = f'(?<spacer>ًا و|أيضا|واو العطف|و)'
    MultiplierRegex = f'\\s*\\b(ألف|مليون|مليار|تريليون)s?\\b'
    CurrencyPrefixList = dict([("Dobra", "ديسيبل | الأمراض المنقولة جنسيا"),
                               ("Dollar", "$"),
                               ("Brazilian Real", "ريال $"),
                               ("United States dollar", "الولايات المتحدة $|us$|us $|u.s. $|u.s $|usd$"),
                               ("East Caribbean dollar", "شرق الكاريبي $"),
                               ("Mexican peso", "mxn$|mxn $|mex$"),
                               ("Australian dollar", "أسترالي $|أستراليا $"),
                               ("Bahamian dollar", "الباهامية $|البهامية $"),
                               ("Barbadian dollar", "بربادوسي $|بربادين $"),
                               ("Belize dollar", "بليز $"),
                               ("Bermudian dollar", "برمودي $"),
                               ("British Virgin Islands dollar",
                                "جزر فيرجن البريطانية $|bvi$|جزر فيرجن $|جزيرة فيرجن $|جزيرة فيرجن البريطانية $"),
                               ("Brunei dollar", "بروناي $|ب$"),
                               ("Sen", "سين"),
                               ("Singapore dollar", "سنغافورة $|s$"),
                               ("Canadian dollar", "الكندي $|can$|c$|c $|canada $"),
                               ("Cayman Islands dollar", "جزر كايمان $|ci$|جزيرة كايمان $"),
                               ("New Zealand dollar", "نيوزيلندا $|nz$|nz $"),
                               ("Cook Islands dollar", "جزر كوك $|جزيرة كوك $"),
                               ("Fijian dollar", "فيجي $|فيجي $"),
                               ("Guyanese dollar", "gy$|gy $|g$|g $"),
                               ("Hong Kong dollar", "هونج كونج $|هونج كونج$|هكد|هونج كونج $"),
                               ("Indian rupee", "₹"),
                               ("Jamaican dollar", "الجامايكي $|j$|جامايكا $"),
                               ("Kiribati dollar", "كيريباتي $"),
                               ("Liberian dollar", "ليبيريا $|ليبيريا $"),
                               ("Micronesian dollar", "ميكرونيزيا $"),
                               ("Namibian dollar", "الناميبي $|nad|n$|ناميبيا $"),
                               ("Nauruan dollar", "ناورو $"),
                               ("Niue dollar", "نيو $"),
                               ("Palauan dollar", "بالاو $"),
                               ("Pitcairn Islands dollar", "جزر بيتكيرن $|جزيرة بيتكيرن $"),
                               ("Solomon Islands dollar", "جزر سليمان $|si$|si $|جزيرة سليمان $"),
                               ("Surinamese dollar", "سورينام $|سورينام $"),
                               ("New Taiwan dollar", "NT$|نت $"),
                               ("Trinidad and Tobago dollar", "ترينيداد وتوباغو $|ترينيداد $|ترينيداد $"),
                               ("Tuvaluan dollar", "توفالو $"),
                               ("Samoan tālā", "ws$"),
                               ("Chinese yuan", "￥"),
                               ("Japanese yen", "¥"),
                               ("Euro", "€"),
                               ("Pound", "£"),
                               ("Costa Rican colón", "₡"),
                               ("Turkish lira", "₺"),
                               ("Bitcoin", "₿|btc|xbt")])
    AmbiguousCurrencyUnitList = [r'din.', r'kiwi', r'kina', r'kobo', r'lari', r'lipa', r'napa', r'para', r'sfr.',
                                 r'taka', r'tala', r'toea', r'vatu', r'yuan', r'all', r'ang', r'ban', r'bob', r'btn',
                                 r'byr', r'cad', r'cop', r'cup', r'dop', r'gip', r'jod', r'kgs', r'lak', r'lei', r'mga',
                                 r'mop', r'nad', r'omr', r'pul', r'sar', r'sbd', r'scr', r'sdg', r'sek', r'sen', r'sol',
                                 r'sos', r'std', r'try', r'yer', r'yen', r'db', r'pen', r'ron', r'mad', r'zar', r'gel',
                                 r'satoshi', r'satoshis']
    BuildPrefix = f'(?<=(\\s|^))'
    BuildSuffix = f'(?=(\\s|\\W|$))'

# pylint: enable=line-too-long
