from .base_numbers import BaseNumbers
# pylint: disable=line-too-long


class CatalanNumericWithUnit:
    CurrencySuffixList = dict([("Dòlar", "dòlar|dòlars|dolar|dolars"),
                                ("Pes", "pes|pesos"),
                                ("Ruble", "ruble|rubles"),
                                ("Lliura", "lliura|lliures"),
                                ("Florín", "florín|florines"),
                                ("Dinar", "dinar|dinars"),
                                ("Franc", "franc|francs"),
                                ("Rupia", "rupia|rupies"),
                                ("Escut", "escut|escuts"),
                                ("Xelín", "xíling|xílins"),
                                ("Lira", "lira|lires"),
                                ("Centau", "centavo|centavos"),
                                ("Cèntim", "cèntim|cèntims"),
                                ("Centèsim", "centèsim|centèsims"),
                                ("Penique", "penique|peniques"),
                                ("Euro", "euro|euros|€|eur"),
                               ("Cèntim d'Euro", "cèntim d'euro|cèntims d'euros"),
                               ("Dòlar del Carib Oriental",
                                "dòlar del carib oriental|dòlars del carib oriental|ec$|xcd"),
                               ("Centau del Carib Oriental", "centau del carib oriental|centaus del carib oriental"),
                               ("Franc CFA d'Àfrica Occidental",
                                "franc cfa d'Àfrica occidental|francs cfa d'Àfrica occidental|fcfa|xof"),
                               ("Cèntim de CFA d'Àfrica Occidental",
                                "cèntim de cfa d'Àfrica occidental|cèntims de cfa d'Àfrica occidental"),
                               ("Franc CFA d'Àfrica Central",
                                "franc cfa d'Àfrica central|francs cfa d'Àfrica central|xaf"),
                               ("Cèntim de CFA d'Àfrica Central",
                                "cèntim de cfa d'Àfrica central|cèntims de cfa d'Àfrica central"),
                               ("Apsar", "apsar|apsares"),
                               ("Afgani afganès", "afgani afganès|؋|afn|afganis|afgani"),
                               ("Pul", "pul|puls"),
                               ("Lek albanès", "lek|lekë|lekes|lek albanès"),
                               ("Qindarka", "qindarka|qindarkë|qindarkas"),
                               ("Kwanza angoleño",
                                "kwanza angoleño|kwanzas angoleños|kwanza angoleño|kwanzas angoleño|kwanzas|aoa|kz"),
                               ("Cêntimo angoleño", "cêntimo angoleño|cêntimo|cêntimos"),
                               ("Florí antillano neerlandès",
                                "florí antillano neerlandès|florins antillano neerlandès|ƒ antillano neerlandès|ang|naƒ"),
                               ("Cent antillano neerlandès", "cent|centen"),
                               ("Riyal saudita", "riial saudita|riials saudita|sar"),
                               ("Halalà saudita", "halalà saudita|hallalah"),
                               ("Dinar algerià", "dinar algerià|dinars algerians|dzd"),
                               ("Cèntim algerià", "cèntim algerià|cèntims algerians"),
                               ("Pes argentí", "pes argentí|pesos argentins|ar$|ars"),
                               ("Centau argentí", "centau argentí|centaus argentins|ctv.|ctius."),
                               ("Dram armeni", "dram armeni|dram armenis|dram|դր."),
                               ("Luma armeni", "luma armeni|luma armenis"),
                               ("Florín arubeño", "florín arubeño|florines arubeños|ƒ arubeños|aƒ|awg"),
                               ("Yotin arubeño", "yotin arubeño|yotines arubeños"),
                               ("Dòlar australià", "dòlar australià|dòlars australians|a$|aud"),
                               ("Centau australià", "centau australià|centaus australians"),
                               ("Manat àzeri", "manat àzeri|man|azn"),
                               ("Qəpik azerí", "qəpik azerí|qəpik"),
                               ("Dòlar bahameño", "dòlar bahameño|dòlars bahameños|b$|bsd"),
                               ("Centau bahameño", "centavo bahameño|centavos bahameños"),
                               ("Dinar bahreiní", "dinar bahreiní|dinars bahrainis|bhd"),
                               ("Fil bahrainí", "fil bahrainí|fils bahrainis"),
                               ("Taka bangladeshí", "taka bangladeshí|taques bangladeshí|bdt"),
                               ("Poisha bangladeshí", "poisha bangladeshí|poishas bangladeshí"),
                               ("Dòlar de Barbats", "dòlar de barbats|dòlars de barbats|bbd"),
                               ("Centau de Barbados", "centau de barbados|centavos de barbados"),
                               ("Dòlar de Belize", "Dòlar de Belize|dòlars de Belize|bz$|bzd"),
                               ("Centau bel·liceny", "centau bel·liceny|centaus bel·licins"),
                               ("Dòlar bermudeño", "dòlar bermudeño|dòlars bermudeños|bd$|bmd"),
                               ("Centau bermudeño", "centavo bermudeño|centavos bermudeños"),
                               ("Ruble bielorus", "ruble bielorus|rubles bielorus|byr"),
                               ("Kòpek bielorus", "kopek bielorús|kopek bielorus|kap"),
                               ("Kyat birmà", "kyat birmà|kyats birmans|mmk"),
                               ("Pya birmà", "pia birmà|pies birmans"),
                               ("Bolivià", "bolivià|bolivians|bob|bs"),
                               ("Centíssim Bolivià", "centèssim bolivià|centèsims bolivians"),
                               ("Marc bosniohercegoví",
                                "marc convertible|marc bosniohercegoví|marcs convertibles|marcs bosniohercegovins|bam"),
                               ("Feningas bosniohercegoví",
                                "feninga convertible|feninga bosniohercegovina|feninges convertibles"),
                               ("Pula", "pula|bwp"),
                               ("Thebe", "thebe"),
                               ("Real brasiler", "real brasiler|reals brasilers|r$|brl"),
                               ("Centau brasiler", "centavo brasiler|centavos brasilers"),
                               ("Dòlar de Brunei", "dòlar de brunei|dòlars de brunei|bnd"),
                               ("Sen de Brunéi", "sense de brunéi"),
                               ("Lev búlgar", "lev búlgar|lleva búlgars|lv|bgn"),
                               ("Stotinki búlgar", "stotinka búlgar|stotinki búlgars"),
                               ("Franc de Burundi", "franc de burundi|francs de burundi|fbu|fib"),
                               ("Cèntim Burundi", "cèntim burundi|cèntims burundies"),
                               ("Ngultrum butanès", "ngultrum butanès|ngultrum butanesos|btn"),
                               ("Chetrum butanès", "chetrum butanès|chetrum butanesos"),
                               ("Escut capverdià", "escut capverdià|escuts capverdians|cve"),
                               ("Riel cambodjà", "riel cambodjà|riels cambodjans|khr"),
                               ("Dòlar canadenc", "dòlar canadenc|dòlars canadencs|c$|cad"),
                               ("Centau canadenc", "centau canadenc|centaus canadencs"),
                               ("Pes xilè", "pes xilè|pesos xilens|cpl"),
                               ("Yuan xinès", "yuan xinès|iuans xinesos|yuan|iuans|renminbi|rmb|cny|￥"),
                               ("Pes colombià", "pes colombià|pesos colombians|cop|col$"),
                                ("Centau colombià", "centau colombià|centaus colombians"),
                                ("Franc comorà", "franc comorà|francs comorans|kmf|₣"),
                                ("Franc congolès", "franc congolès|francs congolesos|cdf"),
                                ("Cèntim congolès", "cèntim congolès|cèntims congolesos"),
                                ("Won nord-coreà", "won nord-coreà|wŏn nord-coreà|wŏn nord-coreans|kpw"),
                                ("Chon nord-coreà",
                                 "chon nord-coreà|chŏn nord-coreà|chŏn nord-coreans|chon nord-coreans"),
                                ("Won sud-coreà", "wŏn sud-coreà|won sud-coreà|wŏnes sud-coreans|wons sud-coreans|krw"),
                                ("Chon sud-coreà", "chon sud-coreà|chŏn sud-coreà|chon sud-coreans|chon sud-coreans"),
                                ("Coló costarricense", "còlon costarricenc|culls costarricencs|crc"),
                                ("Kuna croat", "kuna croat|kuna croat|hrk"),
                                ("Llipa croata", "llipa croata|lipa croates"),
                                ("Pes cubà", "pes cubà|pesos cubans|cup"),
                                ("Pes cubà convertible", "pes cubà convertible|pesos cubans convertible|cuc"),
                                ("Corona danesa", "corona danesa|corones daneses|dkk"),
                                ("Lliura egípcia", "lliura egípcia|lliures egípcies|egp|l.e."),
                                ("Piastra egípcia", "piastra egípcia|piastres egípcies"),
                                ("Coló salvadorenc", "coló salvadorenc|colons salvadorencs|svc"),
                                ("Dirham dels Unió dels Emirats Àrabs",
                                 "dirham|dirhams|dirham dels emirats Àrabs units|aed|dhs"),
                                ("Nakfa", "nakfa|nfk|ern"),
                                ("Cèntim de Nakfa", "cèntim de nakfa|cèntims de nakfa"),
                                ("Pesseta", "pesseta|pessetes|pts.|ptes.|esp"),
                                ("Dòlar nord-americà", "dòlar nord-americà|dòlars nord-americans|usd|u$d|us$"),
                                ("Corona estonia", "corona estonia|corones estonias|eek"),
                                ("Senti estonia", "senti estonia|senti estonias"),
                                ("Birr etíop", "birr etíop|birr etíops|br|etb"),
                                ("Santim etíop", "santim etíop|santim etíops"),
                                ("Pes filipí", "pes filipino|pes pes filipins|php"),
                                ("Marc finlandès", "marc finlandès|marcs finlandesos"),
                                ("Dòlar fiyià", "dòlar fiyià|dòlars fiyians|fj$|fjd"),
                                ("Centau fiyiano", "centavo fiyiano|centavos fiyianos"),
                                ("Dalasi", "dalasi|gmd"),
                                ("Bututs", "butut|bututs"),
                                ("Lari georgià", "lari georgià|lari georgians|gel"),
                                ("Tetri georgià", "tetri georgià|tetri georgians"),
                                ("Cedi", "cedi|ghs|gh₵"),
                                ("Pesewa", "pesewa"),
                               ("Lliura gibraltarenya", "lliura gibraltareña|lliures gibraltarenyes|gip"),
                               ("Penique gibraltareña", "penique gibraltareña|peniques gibraltareñas"),
                               (
                               "Quetzal guatemalenc", "quetzal guatemalenc|quetzals guatemalencs|quetzal|quetzals|gtq"),
                               ("Centau guatemalenc", "centau guatemalenc|centaus guatemalencs"),
                               ("Lliura de Guernsey", "lliura de guernsey|lliures de guernsey|ggp"),
                               ("Penique de Guernsey", "penique de guernsey|peniques de guernsey"),
                               ("Franc guineà", "franc guineà|francs guineans|gnf|fg"),
                               ("Cèntim guineà", "cèntim guineà|cèntims guineans"),
                               ("Dòlar guyanès", "dòlar guyanès|dòlars guyanesos|gyd|gy"),
                               ("Gourde haitiano", "gourde haitiano|gourde haitians|htg"),
                               ("Cèntim haitià", "cèntim haitià|cèntims haitians"),
                               ("Lempira hondureny", "lempira hondureny|lempira hondurenys|hnl"),
                               ("Centau hondureny", "centavo hondureny|centavos hondureny"),
                               ("Dòlar de Hong Kong", "dòlar de hong kong|dòlars de hong kong|hk$|hkd"),
                               ("Forint hongarès", "forint hongarès|forint hongarès|huf"),
                               ("Rúpia índia", "rupia índia|rupies índies|inr"),
                               ("Paisa índia", "paisa índia|paise índies"),
                               ("Rúpia indonèsia", "rupia indonèsia|rupies indonèsies|idr"),
                               ("Sen indonèsia", "sense indonèsia|sense indonèsies"),
                               ("Rial iranià", "rial iranià|rial iranies|irr"),
                               ("Dinar iraquià", "dinar iraquià|dinars iraquís|iqd"),
                               ("Fil iraquià", "fil iraquià|fils iraquís"),
                               ("Lliura manesa", "lliura manesa|lliures maneses|imp"),
                               ("Penique manes", "penique manes|peniques manesos"),
                               ("Corona islandesa", "corona islandesa|corones islandeses|isk|ikr"),
                               ("Aurar islandes", "aurar islandes|aurar islandesos"),
                               ("Dòlar de les Illes Caiman",
                                "dòlar de les illes caiman|dòlars de les illes caiman|ci$|kyd"),
                               ("Dòlar de les Illes Cook", "dòlar de les illes cook|dòlars de les illes cook"),
                               ("Corona feroesa", "corona feroesa|corones feroeses|fkr"),
                               ("Lliura malvinenca", "lliura malvinenca|lliures malvinenques|fk£|fkp"),
                               ("Dòlar de les Illes Salomó",
                                "dòlar de les illes salomón|dòlars de les illes salomón|sbd"),
                               ("Nou shéquel", "nou shéquel|nous shéquel|ils"),
                               ("Agorot", "agorot"),
                               ("Dòlar jamaiquí", "dòlar jamaiquí|dòlars jamaiquins|j$|ja$|jmd"),
                               ("ien", "ien|iens|jpy"),
                               ("Lliura de Jersey", "lliura de jersei|lliures de jersei|jep"),
                               ("Dinar jordà", "dinar jordà|dinars jordans|jd|jod"),
                               ("Piastra jordà", "piastra jordà|piastres jordans"),
                               ("Tenge kazakh", "tenge|tenge kazakh|kzt"),
                               ("Xelín kenià", "xíling kenià|xílings kenyans|ksh|kes"),
                               ("Som kirguís", "som kirguís|kgs"),
                               ("Tyiyn", "tyiyn"),
                               ("Dòlar de Kiribati", "dòlar de kiribati|dòlars de kiribati"),
                               ("Dinar kuwaití", "dinar kuwaití|dinars kuwaití"),
                               ("Kip laosià", "kip|kip laosià|kip laosians|lak"),
                               ("Att laosià", "att|att laosià|att laosians"),
                               ("Loti", "loti|maloti|lsl"),
                               ("Sent", "sent|llisent"),
                               ("Lliura libanesa", "lliura libanesa|lliures libaneses|lbp"),
                               ("Dòlar liberià", "dòlar liberià|dòlars liberians|l$|lrd"),
                               ("Dinar libi", "dinar libi|dinars libis|ld|lyd"),
                               ("Dirham libi", "dirham libi|dirhams libis"),
                               ("Lites lituana", "lites lituana|litai lituanes|ltl"),
                               ("Pataca macaense", "pataca macaense|pataques macaenses|mop$|mop"),
                               ("Avo macaense", "avo macaense|aus macaenses"),
                               ("Ho macaense", "ho macaense|ho macaenses"),
                               ("Denar macedoni", "denar macedoni|denare macedoni|den|mkd"),
                               ("Deni macedoni", "deni macedoni|deni macedonis"),
                               ("Ariary malgaixos", "ariary malgaixos|ariary malgaixos|mga"),
                               ("Iraimbilanja malgaixos", "iraimbilanja malgaixos|iraimbilanja malgaixos"),
                               ("Ringgit malai", "ringgit malai|ringgit malais|rm|myr"),
                               ("Sen malayo", "sen malayo|sen malais"),
                               ("Kwacha malauí", "kwacha malauí|mk|mwk"),
                               ("Tamba malauí", "tamba malauí"),
                               ("Rúpia de Maldives", "rupia de maldives|rupies de maldives|mvr"),
                               ("Dirham marroquí", "dirham marroquí|dirhams marroquins|mad"),
                               ("Rúpia de Maurici", "rupia de Maurici|rupies de Maurici|mur"),
                               ("Uguiya", "uguiya|uguiyas|mro"),
                               ("Jum", "jum|jums"),
                               ("Pes mexicà", "pes mexicà|pesos mexicans|mxn|mxn$|mxn $|mex$"),
                               ("Centau mexicà", "centau mexicà|centaus mexicans"),
                               ("Leu moldau", "leu moldau|llei moldaus|mdl"),
                               ("Ban moldau", "ban moldau|bani moldaus"),
                               ("Tugrik mongol", "tugrik mongol|tugrik|tugrik mongols|tug|mnt"),
                               ("Metical moçambiquès",
                                "metical|metical moçambiquès|meticals|meticals moçambiquesos|mtn|mzn"),
                               ("Dram de Nagorno Karabaj", "dram de nagorno karabaj|drams de nagorno karabaj"),
                               ("Luma de Nagorno Karabakh", "luma de nagorn karabakh"),
                               ("Dòlar namibi", "dòlar namibi|dòlars namibis|n$|nad"),
                               ("Centau namibi", "centau namibi|centaus namibis"),
                               ("Rúpia nepalès", "rupia nepalesa|rupies nepales|npr"),
                               ("Païsa nepalès", "païssa nepalesa|països nepalesos"),
                               ("Còrdova nicaragüenc", "còrdova nicaragüenc|còrdoves nicaragüencs|ni"),
                               ("Centau nicaragüenc", "centau nicaragüenc|centaus nicaragüencs"),
                               ("Naira", "naira|ngn"),
                               ("Kobo", "kobo"),
                               ("Corona noruega", "corona noruega|corones noruegues|nok"),
                               ("Franc CFP", "franc cfp|francs cfp|xpf"),
                               ("Dòlar neozelandès",
                                "dòlar neozelandès|dòlars neozelandesos|dòlar de nova zelanda|dòlars de nova zelanda|nz$|nzd"),
                               ("Centau neozelandès",
                                "centau neozelandès|centau de nova zelanda|centaus de nova zelanda|centaus neozelandesos"),
                               ("Rial omaní", "rial omaní|rials omanies|omr"),
                               ("Baisa omaní", "baisa omaní|baisa omanies"),
                               ("Florí neerlandès", "florí neerlandès|florins neerlandesos|nlg"),
                               ("Rúpia pakistanesa", "rupia pakistanesa|rupies pakistaneses|pkr"),
                               ("Païsa pakistanesa", "paisa pakistanesa|països pakistanesos"),
                               ("Balboa panameny", "balboa panameny|balboa panamenys|pab"),
                               ("Centíssim panameny", "centèsim panameny|centèsims panamenys"),
                               ("Kina", "kina|pkg|pgk"),
                               ("Toea", "toea"),
                               ("Guaraní", "guaraní|guaranies|gs|pyg"),
                               ("Sol", "sol|sols|nou sol|pen|s#."),
                               ("Cèntim de sol", "cèntim de sol|cèntims de sol"),
                               ("Złoty", "złoty|esloti|eslotis|zł|pln"),
                               ("Groszy", "groszy"),
                               ("Riyal qatarià", "riyal qatarià|riyal qatarià|qr|qar"),
                               ("Dirham qatarià", "dirham qatarià|dirhams qataries"),
                               ("Lliura esterlina", "lliura esterlina|lliures esterlines|gbp"),
                               ("Corona txeca", "corona txeca|corones txeques|kc|czk"),
                               ("Pes dominicà", "pes dominicà|pesos dominicans|rd$|dop"),
                               ("Centau dominicà", "centau dominicà|centaus dominicans"),
                               ("Franc ruandès", "franc ruandès|francs ruandesos|rf|rwf"),
                               ("Cèntim ruandès", "cèntim ruandès|cèntims ruandesos"),
                               ("Leu romanès", "leu romanès|llei romanesos|rom"),
                               ("Ban romanès", "ban romanès|bani romanesos"),
                               ("Ruble rus", "ruble rus|rubles russos|rub"),
                               ("Kopek rus", "kopek rus|kopeks russos"),
                               ("Tala", "tala|tālā|ws$|sat|wst"),
                               ("Sene", "sene"),
                               ("Lliura de Santa Helena", "lliura de santa hel·lena|lliures de santa hel·lena|shp"),
                               ("Penique de Santa Helena", "penique de santa hel·lena|peniques de santa hel·lena"),
                               ("Dobra", "dobra"),
                               ("Dinar serbi", "dinar serbi|dinars serbis|rsd"),
                               ("Per a serbi", "per a serbi|per a serbis"),
                               ("Rúpia de Seychelles", "rupia de seychelles|rupies de seychelles|scr"),
                               ("Centau de Seychelles", "centau de seychelles|centaus de seychelles"),
                               ("Leone", "leone|li|sll"),
                               ("Dòlar de Singapur", "dòlar de singapur|dòlars de singapur|sgb"),
                               ("Centau de Singapur", "centau de Singapur|centaus de Singapur"),
                               ("Lliura siriana", "lliura siriana|lliures sirianes|s£|syp"),
                               ("Piastra siriana", "piastra siriana|piastres sirianes"),
                               ("Xelin somali", "xíling somali|xílings somalis|sos"),
                               ("Centau somali", "centau somali|centaus somalies"),
                               ("Xelín somalilandès", "xíling somalilandès|xílings somalilandesos"),
                               ("Centau somalilandès", "centau somalilandès|centaus somalilandesos"),
                               ("Rúpia de Sri Lanka", "rupia de Sri Lanka|rupies de Sri Lanka|lkr"),
                               ("Cèntim de Sri Lanka", "cèntim de Sri Lanka|cèntims de Sri Lanka"),
                               ("Lilangeni", "lilangeni|emalangeni|szl"),
                               ("Rand sud-africà", "rand|rand sud-africà|tsar"),
                               ("Lliura sudanesa", "lliura sudanesa|lliures sudaneses|sdg"),
                               ("Piastra sudanesa", "piastra sudanesa|piastres sudaneses"),
                               ("Lliura sursudanesa", "lliura sursudanesa|lliures sursudanesa|ssp"),
                               ("Piastra sursudanesa", "piastra sursudanesa|piastres sursudaneses"),
                               ("Corona sueca", "corona sueca|corones sueques|sek"),
                               ("Franc suís", "franc suís|francs suïssos|sfr|chf"),
                               ("Rappen suís", "rappen suís|rappens suïssos"),
                               ("Dòlar surinamés", "òolar surinamés|dòlars surinamesos|srd"),
                               ("Centau surinamés", "centau surinamés|centaus surinamés"),
                               ("Baht tailandès", "baht tailandès|baht tailandesos|thb"),
                               ("Satang tailandès", "satang tailandès|satang tailandesos"),
                               ("Nou dòlar taiwanès", "nou dòlar taiwanès|dòlar taiwanès|dòlars taiwanesos|twd"),
                               ("Centau taiwanès", "centau taiwanès|centaus taiwanesos"),
                               ("Xelín tanzano", "xíling tanzano|xílings tanzanos|tzs"),
                               ("Centau tanzano", "centavo tanzano|centavos tanzanos"),
                               ("Somoni tayiko", "somoni tayiko|somoni|tjs"),
                               ("Diram", "diram|dirams"),
                               ("Paʻanga", "dòlar tongan|dòlars tongans|paʻanga|pa'anga|top"),
                               ("Seniti", "seniti"),
                               ("Ruble de Transnistria", "ruble de transnistria|rubles de transnistria"),
                               ("Kopek de Transnistria", "kopek de transnistria|kopeks de transnistria"),
                               ("Dòlar trinitenc", "dòlar trinitenc|dòlars trinitencs|ttd"),
                               ("Centau trinitense", "centavo trinitense|centavos trinitenses"),
                               ("Dinar tunisià", "dinar tunisià|dinars tunisians|tnd"),
                               ("Millime tunisià", "millime tunisià|millimes tunisians"),
                               ("Lira turca", "lira turca|lires turques|try"),
                               ("Kuruş turca", "kuruş turca|kuruş turques"),
                               ("Manat turcman", "manat turcmen|manat turkmenos|tmt"),
                               ("Tennesi turcman", "tennesi turcman|tenge turcman"),
                               ("Dòlar tuvaluà", "dòlar tuvaluà|dòlars tuvaluans"),
                               ("Centau tuvaluà", "centau tuvaluà|centaus tuvaluans"),
                               ("Grivna", "grivna|grivnas|uah"),
                               ("Kopiyka", "kopiyka|kopeks"),
                               ("Xelín ugandès", "xíling ugandès|xílings ugandesos|ugx"),
                               ("Centau ugandès", "centau ugandès|centaus ugandesos"),
                               ("Pes uruguaià", "pes uruguaià|pesos uruguaians|uyu"),
                               ("Centèssim uruguaià", "centèsim uruguaià|centèsims uruguaians"),
                               ("Som uzbeko", "som uzbeko|som uzbekos|uzs"),
                               ("Tiyin uzbeko", "tiyin uzbeko|tiyin uzbekos"),
                               ("Vatu", "vatu|vuv"),
                               ("Bolívar fort", "bolívar fort|bolívar|bolívars|vef"),
                               ("Cèntim de bolívar", "cèntim de bolívar|cèntims de bolívar"),
                               ("Đồng vietnamita", "Đồng vietnamita|dong vietnamita|dong vietnamites|vnd"),
                               ("Hào vietnamita", "Hào vietnamita|hao vietnamita|hao vietnamites"),
                               ("Rial iemenita", "rial iemenit|rials iemenites|yer"),
                               ("Fils iemenita", "fils iemenita|fils iemenites"),
                               ("Franc gibutià", "franc gibutià|francs gibutians|djf"),
                               ("Dinar iugoslau", "dinar iugoslau|dinars iugoslaus|yud"),
                               ("Kwacha zambià", "kwacha zambià|kwacha zambians|zmw"),
                               ("Ngwee zambià", "ngwee zambià|ngwee zambians"),
                               ("Bitcoin", "bitcoin|bitcoins|btc|xbt|₿"),
                               ("Millibitcoin", "millibitcoin|millibitcoins|milibitcoin|milibitcoins"),
                               ("Satoshi", "satoshi|satoshis")])
    CurrencyNameToIsoCodeMap = dict([("Afgani afganès", "AFN"),
                                      ("Euro", "EUR"),
                                      ("Lek albanès", "ALL"),
                                      ("Kwanza angolès", "AOA"),
                                      ("Dram armeni", "AMD"),
                                      ("Florín arubeño", "AWG"),
                                      ("Taka bangladeshí", "BDT"),
                                      ("Ngultrum butanès", "BTN"),
                                      ("Bolivià", "BOB"),
                                      ("Marc bosniohercegoví", "BAM"),
                                      ("Pula", "BWP"),
                                      ("Real brasiler", "BRL"),
                                      ("Lev búlgar", "BGN"),
                                      ("Riel cambodjà", "KHR"),
                                      ("Escut caboverdià", "CVE"),
                                      ("Coló costarricense", "CRC"),
                                      ("Kuna croata", "HRK"),
                                      ("Corona txeca", "CZK"),
                                      ("Nakfa", "ERN"),
                                      ("Birr etíop", "ETB"),
                                      ("Dalasi", "GMD"),
                                      ("Lari georgià", "GEL"),
                                      ("Cedi", "GHS"),
                                      ("Quetzal guatemalenc", "GTQ"),
                                      ("Gourde haitià", "HTG"),
                                      ("Lempira hondureny", "HNL"),
                                      ("Forint hongarès", "HUF"),
                                      ("Rial iranià", "IRR"),
                                      ("Rial iemenita", "YER"),
                                      ("Nou shéquel", "ILS"),
                                      ("Ien", "JPY"),
                                      ("Tenge kazakh", "KZT"),
                                      ("Xelín kenià", "KES"),
                                      ("Won nord-coreà", "KPW"),
                                      ("Won sud-coreà", "KRW"),
                                      ("Som kirguís", "KGS"),
                                      ("Kip laosià", "LAK"),
                                      ("Loti", "LSL"),
                                      ("Rand sud-africà", "ZAR"),
                                      ("Pataca macaense", "MOP"),
                                      ("Denar macedoni", "MKD"),
                                      ("Ariary malgaix", "MGA"),
                                      ("Kwacha malauí", "MWK"),
                                      ("Ringgit malai", "MYR"),
                                      ("Uguiya", "MRO"),
                                      ("Tugrik mongol", "MNT"),
                                      ("Metical moçambiquès", "MZN"),
                                      ("Kyat birmà", "MMK"),
                                      ("Còrdova nicaragüenc", "NIO"),
                                      ("Naira", "NGN"),
                                      ("Lira turca", "TRY"),
                                      ("Rial omaní", "OMR"),
                                      ("Balboa panameny", "PAB"),
                                      ("Kina", "PGK"),
                                      ("Guaraní", "PYG"),
                                      ("Sol", "PEN"),
                                      ("Złoty", "PLN"),
                                      ("Riyal qatarià", "QAR"),
                                      ("Riyal saudita", "SAR"),
                                      ("Tala", "WST"),
                                      ("Són Tomé and Príncep dobra", "STN"),
                                      ("Leone", "SLL"),
                                      ("Lilangeni", "SZL"),
                                      ("Somoni tayiko", "TJS"),
                                      ("Baht tailandès", "THB"),
                                      ("Grivna", "UAH"),
                                      ("Vatu", "VUV"),
                                      ("Bolívar fort", "VEF"),
                                      ("Kwacha zambià", "ZMW"),
                                      ("Dirham marroquí", "MAD"),
                                      ("Dirham dels Unió dels Emirats Àrabs", "AED"),
                                      ("Manat azerí", "AZN"),
                                      ("Manat turkmè", "TMT"),
                                      ("Xelin somali", "SOS"),
                                      ("Xelín tanzano", "TZS"),
                                      ("Xelín ugandès", "UGX"),
                                      ("Leu romanès", "RON"),
                                      ("Leu moldau", "MDL"),
                                      ("Rúpia nepalesa", "NPR"),
                                      ("Rupia pakistanesa", "PKR"),
                                     ("Rúpia índia", "INR"),
                                     ("Rúpia de Seychelles", "SCR"),
                                     ("Rúpia de Maurici", "MUR"),
                                     ("Rúpia de Maldives", "MVR"),
                                     ("Rúpia de Sri Lanka", "LKR"),
                                     ("Rupia indonèsia", "IDR"),
                                     ("Corona danesa", "DKK"),
                                     ("Corona noruega", "NOK"),
                                     ("Corona islandesa", "ISK"),
                                     ("Corona sueca", "SEK"),
                                     ("Franc CFA d'Àfrica Occidental", "XOF"),
                                     ("Franc CFA d'Àfrica Central", "XAF"),
                                     ("Franc comorà", "KMF"),
                                     ("Franc congolès", "CDF"),
                                     ("Burundian franc", "BIF"),
                                     ("Franc gibutià", "DJF"),
                                     ("Franco CFP", "XPF"),
                                     ("Franc guineà", "GNF"),
                                     ("Franc suís", "CHF"),
                                     ("Franc ruandès", "RWF"),
                                     ("Ruble rus", "RUB"),
                                     ("Transnistrian ruble", "PRB"),
                                     ("New Belarusian ruble", "BYN"),
                                     ("Dinar algerià", "DZD"),
                                     ("Dinar bahrainès", "BHD"),
                                     ("Dinar iraquià", "IQD"),
                                     ("Dinar jordà", "JOD"),
                                     ("Kuwaiti dinar", "KWD"),
                                     ("Dinar libi", "LYD"),
                                     ("Dinar serbi", "RSD"),
                                     ("Dinar tunisià", "TND"),
                                     ("Pes argentí", "ARS"),
                                     ("Xilean pes", "CLP"),
                                     ("Pes colombià", "COP"),
                                     ("Pes cubà convertible", "CUC"),
                                     ("Pes cubà", "CUP"),
                                     ("Pes dominicà", "DOP"),
                                     ("Pes mexicà", "MXN"),
                                     ("Pes uruguaià", "UYU"),
                                     ("Lliura esterlina", "GBP"),
                                     ("Lliura de Santa Helena", "SHP"),
                                     ("Lliura egípcia", "EGP"),
                                     ("Lliura malvinenca", "FKP"),
                                     ("Lliura gibraltarenya", "GIP"),
                                     ("Lliura manesa", "IMP"),
                                     ("Lliura de Jersey", "JEP"),
                                     ("Lliura libanesa", "LBP"),
                                     ("Lliura sursudanesa", "SSP"),
                                     ("Lliura sudanesa", "SDG"),
                                     ("Lliura siriana", "SYP"),
                                     ("Dòlar nord-americà", "USD"),
                                     ("Dòlar australià", "AUD"),
                                     ("Dòlar de Bahama", "BSD"),
                                     ("Dòlar de Barbados", "BBD"),
                                     ("Dòlar bel·liceny", "BZD"),
                                     ("Dòlar bermudeny", "BMD"),
                                     ("Dòlar de Brunéi", "BND"),
                                     ("Dòlar de Singapur", "SGD"),
                                     ("Dòlar canadenc", "CAD"),
                                     ("Dòlar de les Illes Caiman", "KYD"),
                                     ("Dòlar neozelandès", "NZD"),
                                     ("Dòlar fiyià", "FJD"),
                                     ("Dòlar guyanès", "GYD"),
                                     ("Dòlar de Hong Kong", "HKD"),
                                     ("Dòlar jamaiquí", "JMD"),
                                     ("Dòlar liberià", "LRD"),
                                     ("Dòlar namíbi", "NAD"),
                                     ("Dòlar de les Illes Salomó", "SBD"),
                                     ("Dòlar surinamés", "SRD"),
                                     ("Nou dòlar taiwanès", "TWD"),
                                     ("Dòlar trinitenc", "TTD"),
                                     ("Tuvaluan dollar", "TVD"),
                                     ("Yuan xinès", "CNY"),
                                     ("Rial", "__RI"),
                                     ("Xelín", "__S"),
                                     ("Som", "__SO"),
                                     ("Dirham", "__DR"),
                                     ("Dinar", "_DN"),
                                     ("Dòlar", "__D"),
                                     ("Manat", "__MA"),
                                     ("Rupia", "__R"),
                                     ("Corona", "__K"),
                                     ("Franco", "__F"),
                                     ("Marc", "__M"),
                                     ("Ruble", "__RB"),
                                     ("Pes", "__PE"),
                                     ("Lliura", "__P"),
                                     ("Tristan dóna Cunha lliura", "_TP"),
                                     ("South Georgia and the South Sandwich Islands lliura", "_SP"),
                                     ("Somaliland xíling", "_SS"),
                                     ("Pitcairn Islands dòlar", "_PND"),
                                     ("Palauan dòlar", "_PD"),
                                     ("Niu dòlar", "_NID"),
                                     ("Nauruan dòlar", "_ND"),
                                     ("Micronesian dòlar", "_MD"),
                                     ("Kiribati dòlar", "_KID"),
                                     ("Guernsey lliura", "_GGP"),
                                     ("Faroese corona", "_FOK"),
                                     ("Cook Islands dòlar", "_CKD"),
                                     ("British Virgin Islands dòlar", "_BD"),
                                     ("Ascensió lliura", "_AP"),
                                     ("Alderney lliura", "_ALP"),
                                     ("Abkhazian apsar", "_AA"),
                                     ("Bitcoin", "_XBT")])
    FractionalUnitNameToCodeMap = dict([("Jiao", "JIAO"),
                                         ("Kópek", "KOPEK"),
                                         ("Kopek", "KOPEK"),
                                         ("Pul", "PUL"),
                                         ("Cent", "CENT"),
                                         ("Qindarka", "QINDARKE"),
                                         ("Penique", "PENNY"),
                                         ("Santeem", "SANTEEM"),
                                         ("Cêntimo", "CENT"),
                                         ("Centau", "CENT"),
                                         ("Luma", "LUMA"),
                                         ("Qəpik", "QƏPIK"),
                                         ("Fils", "FILS"),
                                         ("Poisha", "POISHA"),
                                         ("Kapyeyka", "KAPYEYKA"),
                                         ("Kopyeyka", "KOPYEYKA"),
                                         ("Centime", "CENTIME"),
                                         ("Chetrum", "CHETRUM"),
                                         ("Païsa", "PAISA"),
                                         ("Feningas", "FENING"),
                                         ("Thebe", "THEBE"),
                                         ("Sen", "SEN"),
                                         ("Stotinka", "STOTINKA"),
                                         ("Fen", "FEN"),
                                         ("Cèntim", "CENT"),
                                         ("Lipa", "LIPA"),
                                         ("Haléř", "HALER"),
                                         ("Øre", "ØRE"),
                                         ("Piastre", "PIASTRE"),
                                         ("Santim", "SANTIM"),
                                         ("Oyra", "OYRA"),
                                         ("Butut", "BUTUT"),
                                         ("Tetri", "TETRI"),
                                         ("Pesewa", "PESEWA"),
                                         ("Filler", "FILLER"),
                                         ("Eyrir", "EYRIR"),
                                         ("Dinar", "DINAR"),
                                         ("Agora", "AGORA"),
                                         ("Tiın", "TIIN"),
                                         ("Chon", "CHON"),
                                         ("Jeon", "JEON"),
                                         ("Tyiyn", "TYIYN"),
                                         ("Att", "ATT"),
                                         ("Sent", "SENT"),
                                         ("Dirham", "DIRHAM"),
                                         ("Rappen", "RAPPEN"),
                                         ("Avo", "AVO"),
                                         ("Deni", "DENI"),
                                         ("Iraimbilanja", "IRAIMBILANJA"),
                                         ("Tambala", "TAMBALA"),
                                         ("Laari", "LAARI"),
                                         ("Khoums", "KHOUMS"),
                                         ("Ban", "BAN"),
                                         ("Möngö", "MONGO"),
                                         ("Pya", "PIA"),
                                         ("Kobo", "KOBO"),
                                         ("Kuruş", "KURUS"),
                                         ("Baisa", "BAISSA"),
                                         ("Centíssim", "CENTESIM"),
                                         ("Toea", "TOEA"),
                                         ("Sentim", "SENTIM"),
                                         ("Grosz", "GROSZ"),
                                         ("Sene", "SENE"),
                                         ("Halala", "HALALA"),
                                         ("Per", "PER"),
                                         ("Öre", "ORE"),
                                         ("Diram", "DIRAM"),
                                         ("Satang", "SATANG"),
                                         ("Seniti", "SENITI"),
                                         ("Millime", "MILLIME"),
                                         ("Tennesi", "TENNESI"),
                                         ("Kopiyka", "KOPIYKA"),
                                         ("Tiyin", "TIYIN"),
                                         ("Hào", "HAO"),
                                         ("Ngwee", "NGWEE"),
                                         ("Millibitcoin", "MILLIBITCOIN"),
                                         ("Satoshi", "SATOSHI")])
    CompoundUnitConnectorRegex = f'(?<spacer>i|amb)'
    MultiplierRegex = f'\\s*\\b(((mil\\s+)?el meu|bi|quatri|quinti|sexti|sèpti)ll[oó]n|mil)(és)?\\b'
    CurrencyPrefixList = dict([("Dobra", "db|std"),
                                ("Dòlar", "$|dòlar|dòlars|dolar|dolars"),
                                ("Dòlar nord-americà", "us$|u$d|usd"),
                                ("Dòlar del Carib Oriental", "ec$|xcd"),
                                ("Dòlar australià", "a$|aud"),
                                ("Dòlar de Bahama", "b$|bsd"),
                                ("Dòlar de Barbados", "bds$|bbd"),
                                ("Dòlar bel·liceny", "bz$|bzd"),
                                ("Dòlar bermudeny", "bd$|bmd"),
                                ("Dòlar de Brunéi", "brunèi $|bnd"),
                                ("Dòlar de Singapur", "s$|sgd"),
                                ("Dòlar canadenc", "c$|can$|cad"),
                                ("Dòlar de les Illes Caiman", "ci$|kyd"),
                                ("Dòlar neozelandès", "nz$|nzd"),
                                ("Dòlar fiià", "fj$|fjd"),
                                ("Dòlar guyanès", "gi$|gyd"),
                                ("Dòlar de Hong Kong", "hk$|hkd"),
                                ("Dòlar jamaiquí", "j$|ja$|jmd"),
                                ("Dòlar liberià", "l$|lrd"),
                                ("Dòlar namíbi", "n$|nad"),
                                ("Dòlar de les Illes Salomó", "si$|sbd"),
                                ("Nou dòlar taiwanès", "nt$|twd"),
                                ("Pes mexicà", "mxn|mxn$|mxn $|mex$"),
                                ("Real brasiler", "r$|brl"),
                                ("Guaraní", "₲|gs.|pyg"),
                                ("Dòlar trinitenc", "tt$|ttd"),
                                ("Yuan xinès", "\|cny|rmb"),
                                ("Ien", "\|jpy"),
                                ("Euro", "€|eur"),
                                ("Florín", "ƒ"),
                                ("Lliura", "£"),
                                ("Coló costarricense", "₡"),
                                ("Lira turca", "₺"),
                                ("Bitcoin", "₿|btc|xbt")])
    AmbiguousCurrencyUnitList = [r'le', r'db', r'std']
    BuildPrefix = f'(?<=(\\s|^|\\P{{L}}))'
    BuildSuffix = f'(?=(\\s|\\P{{L}}|$))'
# pylint: enable=line-too-long