#  Copyright (c) Microsoft Corporation. All rights reserved.
#  Licensed under the MIT License.

class Constants:
    IP_REGEX_IPV4: str = "ipv4"
    IP_REGEX_IPV6: str = "ipv6"
    IPV6_ELLIPSIS: str = "::"
    PHONE_NUMBER_REGEX_GENERAL: str = "GeneralPhoneNumber"
    PHONE_NUMBER_REGEX_BR: str = "BRPhoneNumber"
    PHONE_NUMBER_REGEX_UK: str = "UKPhoneNumber"
    PHONE_NUMBER_REGEX_DE: str = "DEPhoneNumber"
    PHONE_NUMBER_REGEX_US: str = "USPhoneNumber"
    PHONE_NUMBER_REGEX_CN: str = "CNPhoneNumber"
    PHONE_NUMBER_REGEX_DK: str = "DKPhoneNumber"
    PHONE_NUMBER_REGEX_IT: str = "ITPhoneNumber"
    PHONE_NUMBER_REGEX_NL: str = "NLPhoneNumber"
    PHONE_NUMBER_REGEX_SPECIAL: str = "SpecialPhoneNumber"
    MENTION_REGEX = "Mention"
    HASHTAG_REGEX = "Hashtag"
    EMAIL_REGEX = "Email"
    URL_REGEX = "Url"
    GUID_REGEX = "Guid"
    SYS_PHONE_NUMBER = "builtin.phonenumber"
    SYS_IP = "builtin.ip"
    SYS_MENTION = "builtin.mention"
    SYS_HASHTAG = "builtin.hashtag"
    SYS_EMAIL = "builtin.email"
    SYS_URL = "builtin.url"
    SYS_GUID = "builtin.guid"
    MODEL_PHONE_NUMBER = "phonenumber"
    MODEL_IP = "ip"
    MODEL_MENTION = "mention"
    MODEL_HASHTAG = "hashtag"
    MODEL_EMAIL = "email"
    MODEL_URL = "url"
    MODEL_GUID = "guid"
