// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

export namespace DutchChoice {
	export const LangMarker = 'Nl';
	export const TokenizerRegex = `[^\\w\\d]`;
	export const TrueRegex = `\\b(ja|jawel|jazeker|natuurlijk|vanzelfsprekend|zeker|prima|jep|yes|yep|y|ok|oke|akkoord)\\b|(\\uD83D\\uDC4D|\\uD83D\\uDC4C)`;
	export const FalseRegex = `\\b(nee|neen|nope|nein|nop|no|niet|nooit)\\b|(\\uD83D\\uDC4E|\\u270B|\\uD83D\\uDD90)`;
}
