// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// ------------------------------------------------------------------------------

package com.microsoft.recognizers.text.sequence.resources;

public class PortuguesePhoneNumbers {

    public static final String NumberReplaceToken = "@builtin.phonenumber";

    public static final String FalsePositivePrefixRegex = "conta(\\s+(número|bancária(\\s+número)?))?(\\s+é)?:?\\s*$";
}
