# ------------------------------------------------------------------------------
# <auto-generated>
#     This code was generated by a tool.
#     Changes to this file may cause incorrect behavior and will be lost if
#     the code is regenerated.
# </auto-generated>
#
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# ------------------------------------------------------------------------------

# pylint: disable=line-too-long


class PortuguesePhoneNumbers:
    NumberReplaceToken = '@builtin.phonenumber'
    FalsePositivePrefixRegex = f'conta(\\s+(número|bancária(\\s+número)?))?(\\s+é)?:?\\s*$'
# pylint: enable=line-too-long
