//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     Generation parameters:
//     - DataFilename: Patterns\Base-HashTag.yaml
//     - Language: NULL
//     - ClassName: BaseHashTag
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Recognizers.Definitions
{
	using System;
	using System.Collections.Generic;

	public static class BaseHashTag
	{
		public const string HashTagRegex = @"(#([a-zA-Z0-9_]+))";
	}
}