//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     Generation parameters:
//     - DataFilename: Patterns\Japanese\Japanese-Choice.yaml
//     - Language: Japanese
//     - ClassName: ChoiceDefinitions
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Recognizers.Definitions.Japanese
{
	using System;
	using System.Collections.Generic;

	public static class ChoiceDefinitions
	{
		public const string LangMarker = "Jpn";
		public const string TokenizerRegex = @"[^\w\d]";
		public const string TrueRegex = @"\b(はい|そうです|そう|よい)\b|(\uD83D\uDC4D|\uD83D\uDC4C)";
		public const string FalseRegex = @"\b(いいえ|ではありません|ではない|じゃない|じゃありません)\b|(\uD83D\uDC4E|\u270B|\uD83D\uDD90)";
	}
}
