// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// ------------------------------------------------------------------------------

export namespace PortuguesePhoneNumbers {
    export const NumberReplaceToken = '@builtin.phonenumber';
    export const FalsePositivePrefixRegex = `conta(\\s+(número|bancária(\\s+número)?))?(\\s+é)?:?\\s*$`;
}
