//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     Generation parameters:
//     - DataFilename: Patterns\English\English-QuotedText.yaml
//     - Language: English
//     - ClassName: QuotedTextDefinitions
// </auto-generated>
//
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// ------------------------------------------------------------------------------

namespace Microsoft.Recognizers.Definitions.English
{
    using System;
    using System.Collections.Generic;

    public static class QuotedTextDefinitions
    {
      public const string LangMarker = @"Eng";
      public const string QuotedTextRegex1 = @"(“([^“”]+)”)";
      public const string QuotedTextRegex2 = @"(‘([^‘’]+)’)";
      public const string QuotedTextRegex3 = @"(""([^""]+)"")";
      public const string QuotedTextRegex4 = @"(\\'([^\']+)\\')";
      public const string QuotedTextRegex5 = @"(`([^`]+)`)";
      public const string QuotedTextRegex6 = @"(123456)";
      public const string QuotedTextRegex7 = @"(123456)";
      public const string QuotedTextRegex8 = @"(123456)";
      public const string QuotedTextRegex9 = @"(123456)";
    }
}